# Generated by Django 5.2 on 2025-04-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_don_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='moyen_paiement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
