# Generated by Django 5.2 on 2025-04-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_don_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='nature_don',
        ),
        migrations.AddField(
            model_name='don',
            name='nature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
