# Generated by Django 5.1.1 on 2025-05-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_tontine_admin',
            field=models.BooleanField(default=False),
        ),
    ]
