# Generated by Django 5.1.1 on 2025-05-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_don_statut_alter_don_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='nom_tontine',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='statut',
            field=models.CharField(choices=[('ATT', 'En attente'), ('VAL', 'Validé'), ('REF', 'Refusé')], default='ATT', max_length=3),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='frequence',
            field=models.CharField(choices=[('H', 'Hebdomadaire'), ('M', 'Mensuelle'), ('T', 'Trimestrielle'), ('A', 'Annuelle')], max_length=1),
        ),
    ]
