# Generated by Django 5.1.1 on 2025-05-13 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_cotisation_nom_tontine_cotisation_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pret',
            name='garant',
        ),
        migrations.AddField(
            model_name='pret',
            name='avaliseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_avalises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pret',
            name='cotisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.cotisation'),
        ),
        migrations.AddField(
            model_name='pret',
            name='infos_avaliseur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pret',
            name='montant_a_rembourser',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pret',
            name='periode_remboursement',
            field=models.CharField(choices=[('1M', '1 mois'), ('3M', '3 mois'), ('6M', '6 mois'), ('1A', '1 an')], default='1M', max_length=2),
        ),
    ]
