# Generated by Django 5.1.1 on 2025-05-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_pret_garant_pret_avaliseur_pret_cotisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='pret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.pret'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='type_remboursement',
            field=models.CharField(choices=[('COT', 'Cotisation'), ('PRET', 'Prêt')], default='COT', max_length=4),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='cotisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.cotisation'),
        ),
    ]
