# Generated by Django 5.1.1 on 2025-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_remboursement_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='montant_deja_rembourse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
