# Generated by Django 5.1.1 on 2025-05-17 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_pret_fichier_avaliseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='date_validation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='cotisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.cotisation'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='pret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.pret'),
        ),
    ]
