# Generated by Django 5.2 on 2025-04-22 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='date_don',
        ),
        migrations.RemoveField(
            model_name='don',
            name='donateur',
        ),
        migrations.AddField(
            model_name='don',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 4, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='don',
            name='methode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='don',
            name='nature_don',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='don',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='don',
            name='type_don',
            field=models.CharField(max_length=50),
        ),
    ]
