# Generated by Django 5.2 on 2025-04-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_don_donateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
