# Generated by Django 5.2 on 2025-04-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_don_moyen_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
