# Generated by Django 5.1.1 on 2025-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_profile_is_tontine_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='statut',
            field=models.CharField(choices=[('ATT', 'En attente'), ('VAL', 'Validé'), ('REF', 'Refusé')], default='ATT', max_length=3),
        ),
        migrations.AlterField(
            model_name='don',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
