# Generated by Django 5.1.1 on 2025-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_remboursement_pret_remboursement_type_remboursement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='fichier_avaliseur',
            field=models.FileField(blank=True, null=True, upload_to='avaliseurs/', verbose_name="Fichier d'informations de l'avaliseur (PDF)"),
        ),
    ]
